---

- name: Node.js app | user
  tags:
  - user
  user:
    name: "{{ node_user }}"
    groups: "www-data"
    shell: /bin/false
    system: yes

- name: Node.js app | git clone
  tags:
  - package
  - git
  git:
    repo: "{{ node_repo }}"
    dest: "/home/{{ node_user }}/{{ node_name }}"
    depth: 1
    force: yes
  notify: restart node

- name: Node.js app | repo perms
  tags:
  - permissions
  file:
    path: "/home/{{ node_user }}/{{ node_name }}"
    owner: "{{ node_user }}"
    group: "{{ node_user }}"
    recurse: yes

- name: Node.js app | service config dir
  tags:
  - dir
  file:
    path: "{{ node_systemd_conf | dirname }}"
    state: directory

- name: Node.js app | service config
  tags:
  - config
  template:
    src: node.conf.j2
    dest: "{{ node_systemd_conf }}"
  notify: restart node

- name: Node.js app | nginx site
  vars: 
    site: "{{ node_name }}"
  include_role:
    name: nginx
    tasks_from: site.yml

- name: Node.js app | systemd service
  tags:
  - systemd
  copy:
    src: "{{ item }}"
    dest: /lib/systemd/system/
  loop:
  - node.service
  - node@.service
  notify: restart node

- name: Node.js app | service
  tags:
  - service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
  - node
  - node@{{ node_name }}

