#! /usr/bin/env ansible-playbook
# Configure node.js webapp
# Replace 'node' with your own inventory group
---
- name: node-app | node.js web app
  hosts: node
  roles:
  - role: node-app
    tags:
    - www
    - webapp
    - node
    - nodejs
